import Link from "next/link";
import { Button, Footer, Header } from "./components";

const dimensions=[["Control","Account ownership and continuity"],["Trust","Credibility and responsible foundations"],["Speed","Real-world mobile performance"],["Conversion","A clear, working enquiry path"],["Resilience","Proven recovery and responsibility"],["Agent readiness","Bounded, supervised workflows"]];
// Managed Website Operations and the Agent Workflow Pilot are omitted until the
// employment, HOSTAFRICA and managed-agent boundaries are approved. Their pages
// exist but are gated — see app/route-policy.ts.
const solutions=[
 ["01","Digital Revenue and Risk Review","A deeper diagnosis for leaders who need evidence, ownership and a 30/60/90-day plan.","/solutions/digital-revenue-risk-review"],
 ["02","Website Revenue System","Clarify the offer, improve the website, prove the enquiry path and establish measurement.","/solutions/website-revenue-system"],
];

export default function Home(){return <><Header/><main>
 <section className="hero"><div className="hero-copy"><p className="eyebrow"><span>01</span> Digital performance for Kenyan businesses</p><h1>Your website should win customers - <em>not quietly lose them.</em></h1><p className="lede">Onduu finds and fixes the weaknesses costing your business enquiries, trust, speed, control and resilience. Start with a six-part Digital Readiness Score and leave with the three actions that matter most.</p><div className="actions"><Button href="/readiness">Get your digital readiness score</Button><a className="text-link" href="#score">See what we check ↓</a></div><p className="signal-line">Control <i/> Trust <i/> Speed <i/> Conversion <i/> Resilience <i/> Agent readiness</p></div><aside className="scorecard" aria-label="Illustrative readiness score sample"><div className="sample-label">Illustrative sample</div><div className="score-heading"><div><small>Digital readiness</small><strong>62<sup>/100</sup></strong></div><div className="dial"><span>62</span></div></div><div className="priority-title"><span>Priority findings</span><small>Evidence status</small></div>{[["01","Enquiry path","Needs evidence"],["02","Recovery proof","Human review"],["03","Mobile speed","Observed"]].map(p=><div className="priority" key={p[0]}><b>{p[0]}</b><span>{p[1]}</span><small>{p[2]}</small></div>)}<p className="caption">A decision tool, not a compliance certificate.</p></aside></section>
 <section className="stakes"><p className="section-number">02 / The quiet cost</p><div><h2>A website can look fine while quietly losing business.</h2><p>The message may be unclear. The enquiry form may not reach the right person. Mobile visitors may wait too long. Nobody may know who controls the domain or analytics.</p></div><blockquote>These are not design preferences. They are failures in a commercial and operational system.</blockquote></section>
 <section className="score-section" id="score"><div className="section-intro"><p className="section-number">03 / The six-part score</p><h2>Know exactly where your digital operation is weak.</h2><p>Every finding shows its evidence source, confidence and limitation.</p></div><div className="dimension-grid">{dimensions.map((d,i)=><article key={d[0]}><span>0{i+1}</span><h3>{d[0]}</h3><p>{d[1]}</p><b>↗</b></article>)}</div><div className="section-action"><Button href="/readiness">Score my website</Button></div></section>
 <section className="method"><div><p className="section-number">04 / The method</p><h2>Start with evidence. Fix the right problem. Measure what changes.</h2></div><div className="method-steps">{[["01","Score","Establish the baseline across six connected dimensions."],["02","Fix","Prioritise the three weaknesses with the greatest consequence."],["03","Measure","Verify the result in enquiries, performance, ownership or recovery."]].map(s=><article key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section>
 <section className="solutions-preview"><div className="section-intro"><p className="section-number">05 / Core solutions</p><h2>A clear path from diagnosis to continuous improvement.</h2><p>Start with the weakness and choose the response that fits.</p></div><div className="solution-list">{solutions.map(s=><Link href={s[3]} key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p><span>Explore ↗</span></Link>)}</div></section>
 <section className="split-feature"><div><p className="section-number">06 / One strategy</p><h2>Your website should express one strategy - not disconnected messages.</h2><p>Align the audience, promise, offer hierarchy, proof, voice, visual rules and calls to action behind one practical source of truth.</p><Button href="/solutions/website-revenue-system">See the website revenue system</Button></div><aside><small>BRAND CLARITY FOUNDATION</small><ol><li>Audience and buying trigger</li><li>Position and promise</li><li>Offer hierarchy</li><li>Proof and limitations</li><li>Voice and visual rules</li><li>CTA map</li></ol></aside></section>
 <section className="dark-feature"><p className="section-number">07 / After launch</p><h2>After launch, the website still needs an owner, a rhythm and a memory.</h2><p>Managed Website Operations connects monitoring, analytics, enquiries, DNS and email-domain health, brand guidance, content priorities and change history into one process.</p><div className="rhythm"><span>Immediate<br/><b>Material alerts</b></span><span>Weekly<br/><b>Owner briefing</b></span><span>Monthly<br/><b>Operating report</b></span><span>Quarterly<br/><b>Readiness review</b></span></div><div className="gate-inline">PREVIEW ONLY - publication requires owner approval</div></section>
 <section className="evidence-section"><div><p className="section-number">08 / Evidence</p><h2>Show the evidence, including what did not work.</h2></div><div><p>Onduu’s first documented studies are in progress. Results will appear only when the customer has consented and the evidence can be shown responsibly.</p><ul><li>Before-and-after readiness scorecards</li><li>Enquiry-path and restore-test evidence</li><li>Speed and accessibility results</li><li>Agent pilot failures and corrections</li></ul><p className="note">Results will be published here once at least one study is approved and consented.</p></div></section>
 <section className="final-cta"><p className="section-number">09 / Your next step</p><h2>Find the three digital weaknesses worth fixing first.</h2><p>Start with a structured score rather than another open-ended sales call.</p><div className="actions"><Button href="/readiness">Get your digital readiness score</Button><Button href="/contact" secondary>Tell me the business problem</Button></div></section>
 </main><Footer/></>}
