import { Link } from "./nav-link";
import { Button, Footer, Header } from "./components";

// Homepage copy from the current strategy (docs/strategy/, 18 Aug 2026;
// exact wording from the 16 Aug two-site decision §6). Onduu educates,
// assesses and routes; it does not deliver implementation.
const dimensions=[
 ["Control","Who owns the accounts, access and renewal responsibilities?"],
 ["Trust","Does the business present credible, consistent and responsible signals?"],
 ["Speed","Can mobile visitors use the important pages without avoidable delay?"],
 ["Conversion","Is there a clear, working route from interest to enquiry?"],
 ["Resilience","Are backup, recovery and operational responsibilities understood?"],
 ["Agent readiness","Are automated workflows bounded, supervised and reversible?"],
];

const knowledge=[
 "Who really controls your domain and DNS?",
 "What a business should know before choosing Kenyan VPS infrastructure.",
 "How to test whether an enquiry form reaches the right person.",
 "What an always-on AI agent needs beyond a VPS.",
 "What email-security checks can and cannot prove.",
 "How to hand a website over without creating dependency.",
];

export default function Home(){return <><Header/><main id="main">
 <section className="hero"><div className="hero-copy"><p className="eyebrow"><span>01</span> Digital readiness for Kenyan businesses</p><h1>Know what is weakening your digital business - <em>and what to do next.</em></h1><p className="lede">Onduu brings websites, conversion, ownership, resilience and infrastructure into one practical view. Use the Digital Readiness Score to identify the gaps, understand the three priorities and continue through the right route: an independent Ujiajiri implementation partner or an official HOSTAFRICA product path.</p><div className="actions"><Button href="/readiness">Check Your Digital Readiness</Button><a className="text-link" href="#paths">See how the paths work ↓</a></div><p className="signal-line">Control <i/> Trust <i/> Speed <i/> Conversion <i/> Resilience <i/> Agent readiness</p></div><aside className="scorecard" aria-label="Illustrative readiness score sample"><div className="sample-label">Illustrative sample</div><div className="score-heading"><div><small>Digital readiness</small><strong>62<sup>/100</sup></strong></div><div className="dial"><span>62</span></div></div><div className="priority-title"><span>Priority findings</span><small>Evidence status</small></div>{[["01","Enquiry path","Needs evidence"],["02","Recovery proof","Human review"],["03","Mobile speed","Observed"]].map(p=><div className="priority" key={p[0]}><b>{p[0]}</b><span>{p[1]}</span><small>{p[2]}</small></div>)}<p className="caption">A decision tool, not a compliance certificate.</p></aside></section>
 <section className="stakes"><p className="section-number">02 / The hidden operational gap</p><div><h2>Your website, hosting and digital tools may work separately while the business journey fails between them.</h2><p>The message can be unclear. The enquiry path can fail. Nobody may own the domain or analytics. Backups may exist without a tested recovery process. A new tool may be added without a responsible operator.</p></div><blockquote>Onduu helps make those gaps visible before you spend money on the wrong fix.</blockquote></section>
 <section className="score-section" id="score"><div className="section-intro"><p className="section-number">03 / Start with a structured view</p><h2>Find the three priorities worth investigating first.</h2><p>The Digital Readiness Score combines safe public observations, information you provide and clearly labelled human judgement. It is a decision aid - not a penetration test, legal opinion, compliance certificate or guarantee of business results.</p></div><div className="dimension-grid">{dimensions.map((d,i)=><article key={d[0]}><span>0{i+1}</span><h3>{d[0]}</h3><p>{d[1]}</p><b>↗</b></article>)}</div><div className="section-action actions"><Button href="/readiness">Check Your Digital Readiness</Button><Link className="text-link" href="/email-security">Run the free email security check ↗</Link></div></section>
 <section className="solutions-preview" id="paths"><div className="section-intro"><p className="section-number">04 / Continue through the right route</p><h2>Onduu explains the problem. The appropriate provider delivers the solution.</h2><p>Implementation and infrastructure are supplied by the parties responsible for them - not by Onduu.</p></div><div className="solution-list"><Link href="/paths/website-and-digital-marketing"><b>01</b><h3>Website and digital-marketing implementation</h3><p>Browse independent implementation partners through Ujiajiri. Each partner publishes its own capabilities and contracts directly with the client. Ujiajiri and Onduu do not quote, collect payment for or guarantee the partner&apos;s work.</p><span>Find an Ujiajiri Partner ↗</span></Link><Link href="/paths/hostafrica-infrastructure"><b>02</b><h3>Domains, hosting, email and VPS infrastructure</h3><p>Continue through an official HOSTAFRICA destination for product information, ordering, billing, provisioning, renewal and product support. Onduu explains suitable use cases and responsibilities but does not resell or support the product.</p><span>Explore the HOSTAFRICA Path ↗</span></Link></div></section>
 <section className="split-feature"><div><p className="section-number">05 / A practical framework</p><h2>Treat the website as a commercial system - not a collection of pages.</h2><p>The Website Revenue System is Onduu&apos;s framework for aligning the audience, offer, proof, page journey, enquiry route and measurement. Use the guide to define the work, then select an independent Ujiajiri partner if implementation is required.</p><Button href="/guides/website-revenue-system">Read the Website Revenue System Guide</Button></div><aside><small>THE SIX WORKSTREAMS</small><ol><li>Brand clarity foundation</li><li>Customer journey and conversion</li><li>Premium website build</li><li>Measurement and lead path</li><li>Trust and continuity</li><li>Launch and handover</li></ol></aside></section>
 <section className="evidence-section"><div><p className="section-number">06 / Tested guidance</p><h2>Understand the responsibility before adopting the technology.</h2></div><div><ul>{knowledge.map(k=><li key={k}>{k}</li>)}</ul><Link className="text-link" href="/guides">Explore the Guides ↗</Link></div></section>
 <section className="method"><div><p className="section-number">07 / Skills into opportunity</p><h2>Ujiajiri helps practical digital skills lead toward self-employment and partner work.</h2></div><div className="method-steps"><article><b>·</b><h3>The pathway</h3><p>Building practical digital skills? Ujiajiri is developing a pathway for young people to learn through practical work, demonstrate capability and connect with independent delivery partners. <a href="https://ujiajiri.ke/for-youth/" target="_blank" rel="noopener noreferrer">Explore the Ujiajiri youth pathway</a>. Product-specific HOSTAFRICA training and programme claims will appear only after formal approval.</p></article><article><b>·</b><h3>The status</h3><p>Ujiajiri connects businesses with independent website and digital-marketing providers through private curated introductions. <a href="https://ujiajiri.ke/request-an-introduction/" target="_blank" rel="noopener noreferrer">Request an implementation introduction</a>. The provider you approve contracts with you directly; the youth pathway remains under development.</p></article></div></section>
 <section className="evidence-section"><div><p className="section-number">08 / Evidence</p><h2>Publish what was tested, including the limits.</h2></div><div><p>Onduu will publish methods, sample outputs, controlled experiments and approved case evidence. Every result should state the source, date, scope and limitation. Partner results remain the partner&apos;s evidence and must not be presented as Onduu&apos;s delivery record.</p></div></section>

 </main><Footer/></>}
